Using Asian Paints stock data from Dec 24, 2019 to Dec 23, 2021.

In [1]:
# Import the libraries
import pandas as pd
import numpy as np

In [2]:
# Load the dataset
df = pd.read_csv("ASIANPAINT.NS.csv")
df.head()

Date         Open         High          Low        Close  \
0  2019-12-24  1812.000000  1826.000000  1799.050049  1803.449951   
1  2019-12-26  1799.400024  1819.699951  1797.050049  1809.599976   
2  2019-12-27  1811.000000  1826.000000  1800.599976  1812.250000   
3  2019-12-30  1810.000000  1818.449951  1798.699951  1802.300049   
4  2019-12-31  1805.000000  1805.000000  1781.099976  1784.949951   

     Adj Close   Volume  
0  1780.978882   896574  
1  1787.052246  1161570  
2  1789.669189   930468  
3  1779.843262   562492  
4  1762.709229   928396

In [3]:
df.shape

(498, 7)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 498 entries, 0 to 497
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Date       498 non-null    object 
 1   Open       498 non-null    float64
 2   High       498 non-null    float64
 3   Low        498 non-null    float64
 4   Close      498 non-null    float64
 5   Adj Close  498 non-null    float64
 6   Volume     498 non-null    int64  
dtypes: float64(5), int64(1), object(1)
memory usage: 27.4+ KB


In [5]:
# Dropping unnecessary columns
df.drop(columns=['Open', 'Close', 'Adj Close', 'Volume'], inplace=True)
df.head()

Date         High          Low
0  2019-12-24  1826.000000  1799.050049
1  2019-12-26  1819.699951  1797.050049
2  2019-12-27  1826.000000  1800.599976
3  2019-12-30  1818.449951  1798.699951
4  2019-12-31  1805.000000  1781.099976

In [6]:
# Taking new column Price, average of High & Low
df['Price'] = (df['High'] + df['Low'])/2
df.head()

Date         High          Low        Price
0  2019-12-24  1826.000000  1799.050049  1812.525024
1  2019-12-26  1819.699951  1797.050049  1808.375000
2  2019-12-27  1826.000000  1800.599976  1813.299988
3  2019-12-30  1818.449951  1798.699951  1808.574951
4  2019-12-31  1805.000000  1781.099976  1793.049988

In [7]:
# Take only Date & Price for further calculations
data = df[['Date', 'Price']]
data = pd.DataFrame(data)
data.head()

Date        Price
0  2019-12-24  1812.525024
1  2019-12-26  1808.375000
2  2019-12-27  1813.299988
3  2019-12-30  1808.574951
4  2019-12-31  1793.049988

## Task 1
Generate One Step Transition Probability Matrix for depreciation/appreciation of 10%, 8%, 5%, 2% and 1%.

In [8]:
# Convert Price column to list
prices = df['Price'].tolist()
print(prices)

[1812.5250245, 1808.375, 1813.299988, 1808.574951, 1793.049988, 1792.875, 1791.650024, 1763.425049, 1716.0, 1725.75, 1715.5, 1758.0, 1778.6500245, 1801.1499635, 1813.2250365, 1827.549988, 1838.375, 1826.950012, 1847.924988, 1818.2000125, 1792.7749635, 1773.049988, 1790.075012, 1792.875, 1783.5, 1792.424988, 1797.450012, 1806.3499755, 1818.950012, 1875.9000245, 1878.075012, 1863.700012, 1863.549988, 1854.9749755, 1883.625, 1897.449951, 1885.0, 1884.825012, 1882.049988, 1870.450012, 1872.049988, 1862.5250245, 1833.5, 1831.875, 1832.5, 1831.2249755, 1812.625, 1803.3499755, 1792.5, 1830.75, 1867.049988, 1859.700012, 1881.950012, 1878.25, 1844.9000245, 1756.799988, 1727.575012, 1724.9000245, 1683.2750245, 1542.574951, 1663.9750365, 1570.375, 1525.625, 1525.674988, 1612.0, 1607.7249755, 1589.2750245, 1645.9000245, 1619.625, 1566.625, 1586.5, 1643.9000245, 1648.9249875, 1653.25, 1710.2750245, 1718.5250245, 1755.3999635, 1732.150024, 1726.9749755, 1767.125, 1823.2250365, 1828.4000245, 1838.950

In [9]:
# Make the One Step Transition Matrix and One Step Transition Probability Matrix
depreciation = [0.1, 0.08, 0.05, 0.02, 0.01]

for p in depreciation:
    prev_price = prices[0]
    last_stage = 1
    P = np.zeros([3, 3])
    TPM = np.zeros([3, 3])
    for day_price in prices[1:]:
        if (day_price - prev_price)/prev_price < -p:
            next_stage = 0
            P[last_stage, next_stage] += 1
            last_stage = 0
        elif (day_price - prev_price)/prev_price > -p and (day_price - prev_price)/prev_price < p:
            next_stage = 1
            P[last_stage, next_stage] += 1
            last_stage = 1
        else:
            next_stage = 2
            P[last_stage, next_stage] += 1
            last_stage = 2
        prev_price = day_price
    
    for i in range(0, 3):
        for j in range(0, 3):
            TPM[i, j] = P[i, j]/np.sum(P[i])
    TPM[np.isnan(TPM)] = 0
            
    print("For depreciation of {}%, One step transition matrix is: \n".format(p*100))
    print(P)
    print("\n")
    print("Corresponding One step transition probability matrix is :\n")
    print(TPM)
    print("\n")

For depreciation of 10.0%, One step transition matrix is: 

[[  0.   0.   0.]
 [  0. 497.   0.]
 [  0.   0.   0.]]


Corresponding One step transition probability matrix is :

[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]


For depreciation of 8.0%, One step transition matrix is: 

[[  0.   1.   0.]
 [  1. 495.   0.]
 [  0.   0.   0.]]


Corresponding One step transition probability matrix is :

[[0.         1.         0.        ]
 [0.00201613 0.99798387 0.        ]
 [0.         0.         0.        ]]


For depreciation of 5.0%, One step transition matrix is: 

[[  0.   1.   1.]
 [  1. 487.   3.]
 [  1.   3.   0.]]


Corresponding One step transition probability matrix is :

[[0.         0.5        0.5       ]
 [0.00203666 0.99185336 0.00610998]
 [0.25       0.75       0.        ]]


For depreciation of 2.0%, One step transition matrix is: 

[[  8.  17.   1.]
 [ 16. 374.  36.]
 [  2.  35.   8.]]


Corresponding One step transition probability matrix is :

[[0.30769231 0.65384615 0.03846154]
 [

<ipython-input-9-085d029098e8>:26: RuntimeWarning: invalid value encountered in double_scalars
  TPM[i, j] = P[i, j]/np.sum(P[i])


## Task 2
Suppose, we have ₹1,00,000. On Dec 24, 2019, we will buy stocks with that money and hold it until the day when the price is depreciated by 10% or more. Then we will sell it and again buy with the money received when the price is depreciated by 10% or more. We will do this upto Dec 23, 2021. We will try this for depreciation by 10%, 8%, 5%, 2% and 1%..

In [55]:
for p in depreciation:    
    money_hand = 100000
    prev_price = prices[0]
    n = money_hand/prev_price
    money_hand = 0

    for day_price in prices[1:]:
        if (day_price - prev_price)/prev_price < -p:
            if n > 0:
                money_hand = n * day_price
                n = 0
            else:
                n = money_hand/day_price
                money_hand = 0
        else:
            pass
        prev_price = day_price

    if n>0:
        money_hand = n * day_price
    else:
        money_hand = money_hand

    print("For depreciation of {}%, after 2 years, I have ₹{}".format(p*100, money_hand))

For depreciation of 10.0%, after 2 years, I have ₹180905.0858155476
For depreciation of 8.0%, after 2 years, I have ₹85106.40847154826
For depreciation of 5.0%, after 2 years, I have ₹177702.55759775158
For depreciation of 2.0%, after 2 years, I have ₹135557.59498870242
For depreciation of 1.0%, after 2 years, I have ₹167494.17527789876
